### PR TITLE
Compatibility issue fixes

### PR DESCRIPTION
**Pull request by ahukkanen**
Fixed compatibility issues with recent money gem.

Fixes also #45.

### CODE REVIEW

**Comment by ahukkanen** [comment]
There is still one test that does not pass because it relates to the historical exchange rates.

Not quite sure how to fix that since I'm not perfectly familiar with the API in the `money` gem. It seems it might even require writing a new store implementation in order to achieve that properly within the provided API methods.

**Comment by semmons99** [comment]
this changes some fundamental APIs. Probably a little too far reaching. Especially with the specs failing.

**Comment by ahukkanen** [comment]
@semmons99 So does the new version of the money gem change these APIs as well. This should probably follow that.

Yeah, and I don't know how to fix the historical rates with the current API methods provided by the money gem. This would need some input from someone else. I understand that this is the only test failing in the test set.

**Comment by semmons99** [comment]
From what I saw in the gem, you can still access the mutex, just via an attr_reader instead.

- shane

**Comment by ahukkanen** [comment]
That's what I thought at first as well but actually I thinke the attr_reader is there by mistake (from the previous version). The variable has been moved to the store object and it's not directly accessible from there. Only through the `transaction` method.

Check the commit that is linked above, it removes the variable from the bank object.

**Comment by semmons99** [comment]
Have you checked how the google_currency gem solved this?

Also, I'm okay releasing this as 2.0 and breaking backwards compatibility if everyone wants that.

- shane

**Comment by ahukkanen** [comment]
Cool, yeah I think the money gem also removes backwards compatibility with the newer versions. Plus this version wouldn't even be compatible with the older versions of the money gem, so I think that needs to happen anyways.

For the google_currency gem, I don't see that they support historical exchange rates or did you mean something else? However, it seems that they extend the store object with their own module at the initializer:
https://github.com/RubyMoney/google_currency/blob/11c6dc5af34c114542eb2696e4a1262e54e5d007/lib/money/bank/google_currency.rb#L50

I think a similar approach might actually work here too and would be a good idea.

I can check into that tomorrow, it's getting pretty late here already.

**Comment by semmons99** [comment]
Thanks!

- shane

**Comment by ahukkanen** [comment]
The backwards compatibility issues are now resolved regarding the historical rates. The test set now passes for all others than jruby-19.

I was also thinking should we rename the class names to match the money gem (e.g. check google_currency) but this might be a problem with the backwards compatibility.

It seems that the test failing for jruby is related to thread safety. The rates seem to be mixed with even and odd records as the rates are probably read at the same time while they are updated by another thread.

If you have any good ideas on how to fix the remaining issue, I'm more than happy to hear them. I've been trying to find out the reason but so far haven't found.

**Comment by ahukkanen** [comment]
Just noticed that the money gem is running the tests against a different version of jruby. Can we try that here as well if it would work better?

**Comment by semmons99** [comment]
That'd be great. Just update Travis.yml
- shane

**Comment by ahukkanen** [comment]
Updated.

Seems like the same problem exists with the same jruby version as they are using in the money gem...

**Comment by ahukkanen** [comment]
Tests seem to pass but it really doesn't mean anything since there was just something I just tried and reverted back to original.

I installed the same version of jruby (9.0.4.0) for me and I can still get it to fail if I increase the amount of loops in that failing test to 1000. In fact, it also fails for "normal ruby" with that amount of loops so there is still something wrong regarding thread safety.

**Comment by ahukkanen** [comment]
Now the checks seem to pass again but it really doesn't say anything as it fails more often than it successfully completes.

So, I'm basically out of luck with the thread safety issue.

I tried this:
https://github.com/mainio/eu_central_bank/commit/f95a7281d61299ae62bf006fceab1f82399473cb

And it seems that at least on my computer it fails quite lot less often with that. But it still fails if the number of iterations is increased, so it's not really a working solution.

Any help is welcome here...

**Comment by ahukkanen** [comment]
OK, I think I finally cracked this with the latest commit.

This is also what I tried to accomplish in the previous commits without thinking this further. Now I went through the old code base with the new one side-by-side and I think this should be now working similarly to the old code.

I have also locally tested this and ran both spec tests that were occasionally failing with jruby ("should update update_rates atomically" and "should exchange money atomically") with more iterations than in the default set. The first one I tested up to 10 000 iterations (which seemed to be enough to make it constantly fail before) and the second one I tested up to 1 000 000 iterations.

So, I'm quite confident this should be now finally fixed but please feel free to run the tests still on your own.

**Comment by semmons99** [comment]
Thanks for working this through to the end.

**Pull request merged**
