### PR TITLE
Update money dependency

### PR DESCRIPTION
**Pull request by kevTheDev**
I've updated the money dependency to the latest version.

By the way, your test suite has failures on the master branch, I had a quick look but not sure what's going on.

### CODE REVIEW

**Comment by semmons99** [comment]
master is passing. The build failure appears to happen on your 'tidy xml' commit.

**Comment by kevTheDev** [comment]
Just cloned the repo afresh and running the specs on master still getting the same 3 failures:

eu_central_bank_spec.rb:39

**Comment by kevTheDev** [comment]
hello - not sure whats going on, but I've removed the tidy XML commit, so if the build is passing would there be any chance of getting a new gem released when you have time.

All the best

kev

**Comment by kevTheDev** [comment]
well I can see that the build is not passing on my branch anyway :(

**Comment by semmons99** [comment]
I fixed master. LTL was removed from the supported currencies. Can you rebase your PR. It should then pass and I can merge and cut a new release. Ping me when you do so.

**Comment by kevTheDev** [comment]
Hi there,

All done.

Cheers

**Comment by semmons99** [comment]
Please remove your changes to the version number. I need to do that when releasing the new version.

**Comment by semmons99** [comment]
let me know when your change just includes the dependency update

**Comment by kevTheDev** [comment]
done

**Comment by semmons99** [comment]
Thanks!

**Comment by semmons99** [comment]
0.5.0 released

**Pull request merged**
