### PR TITLE
Allow bumps in minor version from dependent gems

### PR DESCRIPTION
**Pull request by jphastings**
I've made a very small change to the `gemspec` which makes this gem compatible with the latest version of RubyMoney (and any future versions which are compatible with the [SemVer](http://semver.org/) versioning used).

### CODE REVIEW

**Comment by jphastings** [comment]
Looks like the tests are failing anyway; I'll see if I can put some time into fixing them up too, but please consider this PR as it stands.

**Comment by jphastings** [comment]
Hmmm, looks as though this breaks the tests on Travis. I'll look into that.

**Comment by takiy33** [comment]
Thank you for PR.

**Comment by takiy33** [comment]
Thank you for Pull Request.
I will close this due to inactivity.

**Pull request closed without merging**
