### PR TITLE
Allow more recent versions of Nokogiri

### PR DESCRIPTION
**Pull request by camertron**
It would be great to be able to use more recent versions of Nokogiri, specifically ones that are compatible with the new Ruby 2.6 release :)

### CODE REVIEW

**Comment by antstorm** [comment]
@camertron great change, thank you! 👍

**Comment by camertron** [comment]
Awesome, thank you @antstorm! Could I also request a new version be published?

**Comment by antstorm** [comment]
@camertron done, 1.4.1 should be available via RubyGems

**Comment by camertron** [comment]
Thank you!

**Pull request merged**
